### ISSUE TITLE
Generated stylesheet generate wrong font weight

### ISSUE THREAD

**Issue by ImBobby** [suitmedia/WFG#4]
All `font-weight` value for bold, normal or thin font are normal. generated stylesheet shown below, notice that all `font-weight` value are all same.

``` CSS
@font-face {
    font-family: 'Roboto';
    src: url('Roboto-Bold.eot');
    src: url('Roboto-Bold.eot?#iefix') format('embedded-opentype'),
         url('Roboto-Bold.woff2') format('woff2'),
         url('Roboto-Bold.woff') format('woff'),
         url('Roboto-Bold.ttf') format('truetype');

    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'Roboto';
    src: url('Roboto-Light.eot');
    src: url('Roboto-Light.eot?#iefix') format('embedded-opentype'),
         url('Roboto-Light.woff2') format('woff2'),
         url('Roboto-Light.woff') format('woff'),
         url('Roboto-Light.ttf') format('truetype');

    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'Roboto';
    src: url('Roboto-Medium.eot');
    src: url('Roboto-Medium.eot?#iefix') format('embedded-opentype'),
         url('Roboto-Medium.woff2') format('woff2'),
         url('Roboto-Medium.woff') format('woff'),
         url('Roboto-Medium.ttf') format('truetype');

    font-weight: normal;
    font-style: normal;
}
```

For each weight should have proper `font-weight` value.
